### ISSUE TITLE
How to identify Video watched full?

### ISSUE THREAD

**Issue by naveenkumarmallappa** [vimeo/vimeo-deeplink-android#19]
#### Issue Summary
How to identify Video watched full?

#### Reproduction Steps
I need to get the progress of that video from Vimeo app.
Is there any support for OnActivityResult? Or any callback

#### Expected Behavior
I need to make an necessary action once video watched full.

**Comment by kevinzetterstrom** [comment]
Hi @naveenkumarmallappa 

Unfortunately there are no hooks within the Vimeo app that will let other apps know about the progress of a video that was watched in the Vimeo app. There is no current plan to add any such hooks.

**Comment by kevinzetterstrom** [comment]
Closing this since it is not a feature we plan to support.
